### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by SamSharp01** [Sharp-Gaming/VTMS#9]
Add Caption on slider like this https://i.imgur.com/qEO5C1k.png

**Comment by JamesKingdom** [comment]
Can you provide what text should be there

**Comment by SamSharp01** [comment]
<h3>Sharp Logistics</h3>
<p>Virtual Trucking Management System</p> thats all it should show on all slides that are on the slider

**Comment by JamesKingdom** [comment]
```
<div class="carousel-caption">
    <h3>Slide Title</h3>
    <p>Slide Caption</p>
</div>
```
